server:
  port: 10000
spring:
  application:
    name: mskx-epidmics-gatway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
    gateway:
      routes:
        - id: system-serve
          uri: lb://system-serve
          predicates:
            - Path=/*/**

